#!/usr/bin/env python3
"""
Weekly Hermes Runner for LifeOS
Generates a Weekly Dispatch blog post and optionally Architecture Proposals.

Digest-first approach (primary):
  1. Read weekly digest from knowledge/news/digest/ (generated by weekly_tldr_process.py)
  2. Single LLM call to write dispatch from digest content
  3. Save locally + push to GitHub (idempotent)

Fallback (no digest available):
  1. Collect raw TLDR articles
  2. LLM selects top 5-7
  3. Fetch full text of selected articles
  4. LLM writes dispatch
  5. Save locally + push to GitHub
"""

import sys
import os
import re
import random
import sqlite3
import datetime
from pathlib import Path

def load_env():
    env_path = Path(__file__).resolve().parent.parent / ".env"
    if env_path.exists():
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    val = val.strip().strip("'\"")
                    os.environ[key] = val

load_env()

BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "indexes" / "lifeos.db"

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from src.core.db import get_db_connection

from scripts.triage_outbox import triage_notes
from src.core.llm_client import call_llm
from src.core.web import fetch_webpage_content
from src.core.agent_harness import execute_with_repair


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

NEWS_DIR: Path = BASE_DIR / "knowledge" / "news"
DIGEST_DIR: Path = NEWS_DIR / "digest"
FETCH_CAP_CHARS: int = 4000       # per-article fetch cap in fallback path
DISPATCH_MAX_TOKENS: int = 7000   # generous budget for full dispatch
DISPATCH_TEMPERATURE: float = 0.4


# ---------------------------------------------------------------------------
# Digest helpers
# ---------------------------------------------------------------------------

def find_latest_digest() -> Path | None:
    """Find the most recent weekly digest in DIGEST_DIR.

    Digest files are named ``tldr-weekly-YYYY-MM-DD-wYYYYWNN.md``
    and generated by :func:`weekly_tldr_process.main`.
    """
    if not DIGEST_DIR.exists():
        return None
    digests = sorted(DIGEST_DIR.glob("tldr-weekly-*.md"))
    return digests[-1] if digests else None


# ---------------------------------------------------------------------------
# Article collection (used for URL cross-referencing + fallback)
# ---------------------------------------------------------------------------

def collect_articles_from_notes(days: int = 7) -> list[dict]:
    """Scan TLDR notes from last N days and extract article metadata."""
    if not NEWS_DIR.exists():
        return []

    now = datetime.datetime.now()
    cutoff = now - datetime.timedelta(days=days)
    articles: list[dict] = []

    for f in sorted(NEWS_DIR.glob("tldr_*.md")):
        mtime = datetime.datetime.fromtimestamp(f.stat().st_mtime)
        if mtime < cutoff:
            continue

        content = f.read_text(encoding="utf-8")
        source_match = re.search(r"Source:\s*(https?://\S+)", content)
        source_url = source_match.group(1) if source_match else f.name

        # Try NEW structured format first (## Articles with ### blocks)
        structured = re.findall(
            r"### (.+?)\n- \*\*URL:\*\* (.+?)\n.*?- \*\*Read time:\*\* (.+?)\n- \*\*TLDR Summary:\*\* (.+?)(?=\n###|\n## |$)",
            content, re.DOTALL,
        )
        if structured:
            for title, url, read_time, summary in structured:
                articles.append({
                    "title": title.strip(),
                    "url": url.strip(),
                    "read_time": read_time.strip(),
                    "summary": summary.strip()[:300],
                    "source": source_url,
                })
        else:
            # OLD format: extract what we can from flat text
            links = re.findall(r"\[([^\]]+)\]\((https?://[^\)]+)\)", content)
            for text, url in links:
                # Skip TLDR internal links and sponsor links
                if "tldr.tech" in url or "sponsor" in text.lower():
                    continue
                articles.append({
                    "title": text.strip()[:120],
                    "url": url.strip(),
                    "read_time": "Unknown",
                    "summary": "",
                    "source": source_url,
                })

    # Deduplicate by URL
    seen: set[str] = set()
    unique: list[dict] = []
    for a in articles:
        if a["url"] not in seen:
            seen.add(a["url"])
            unique.append(a)

    return unique


def build_candidates_prompt(articles: list[dict]) -> str:
    """Build a compact article list for LLM selection (fallback path only)."""
    lines: list[str] = []
    for i, a in enumerate(articles, 1):
        lines.append(f"{i}. **{a['title']}**")
        lines.append(f"   Source: {a['source']}")
        lines.append(f"   URL: {a['url']}")
        if a["summary"]:
            lines.append(f"   Summary: {a['summary'][:200]}")
        if a["read_time"] != "Unknown":
            lines.append(f"   Read time: {a['read_time']}")
        lines.append("")
    return "\n".join(lines)


def build_url_reference(articles: list[dict]) -> str:
    """Build a compact URL reference for the LLM to link articles in the dispatch."""
    lines = ["## Article URL Reference"]
    for i, a in enumerate(articles, 1):
        lines.append(f"{i}. [{a['title'][:100]}]({a['url']})")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Output sanitisation
# ---------------------------------------------------------------------------

def strip_artifacts(dispatch: str) -> str:
    """Remove template instruction artifacts from LLM output."""
    # Strip "Sample dispatch generated for format review" if the LLM included it
    dispatch = re.sub(
        r"> \*Sample dispatch generated for format review[^\n]*\n(\n)?",
        "", dispatch, count=1,
    )
    # Strip footer: "Generated by Hermes..." + "Review, edit, and publish..."
    dispatch = re.sub(
        r"\n?\*Generated by Hermes[^\n]*\n\*Review, edit, and publish[^\n]*\*",
        "", dispatch, count=1,
    )
    # Also strip standalone "Review, edit..." lines if footer was split
    dispatch = re.sub(
        r"\n\*Review, edit, and publish at your discretion[^\n]*\*",
        "", dispatch, count=1,
    )
    return dispatch.rstrip() + "\n"


# ---------------------------------------------------------------------------
# GitHub push (idempotent)
# ---------------------------------------------------------------------------

def push_to_github(dispatch: str, today: str) -> bool:
    """Push the dispatch to the website repo on GitHub.

    Checks for existing file first to make the operation idempotent
    (``create_file`` would throw 422 on a second run).
    """
    github_token = os.environ.get("WEBSITE_GITHUB_TOKEN")
    github_repo = os.environ.get("WEBSITE_GITHUB_REPO")
    if not github_token or not github_repo:
        print("GitHub token/repo not configured. Skipping push.")
        return False
    if "No dispatch generated" in dispatch:
        print("Dispatch is placeholder. Skipping push.")
        return False

    print("Phase 3: Deploying newsletter to GitHub for TinaCMS...")
    try:
        from github import Github
        from github import Auth

        now_iso = datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%S.000Z",
        )

        # Strip the H1 title + template wrapper; keep body from ## Top Stories onward
        if "## 🔥 Top Stories This Week" in dispatch:
            parts = dispatch.split("## 🔥 Top Stories This Week", 1)
            body_content = "# 🔥 Top Stories This Week" + parts[1]
        else:
            body_content = dispatch

        # Auto-generate description from first blockquote or first paragraph
        desc = ""
        bt_match = re.search(r"^>\s*\*(.+?)\*", dispatch, re.MULTILINE)
        if bt_match:
            desc = bt_match.group(1).strip()[:120]
        if not desc:
            for line in dispatch.split("\n"):
                line = line.strip()
                if line and not line.startswith("#") and not line.startswith("---") and not line.startswith(">"):
                    desc = line[:120]
                    break
        if not desc:
            desc = f"Weekly dispatch for {today}"

        frontmatter = (
            f"---\n"
            f"title: LifeOS Weekly Dispatch — {today}\n"
            f"description: '{desc}'\n"
            f"type: build-log\n"
            f"pubDate: {now_iso}\n"
            f"tags:\n"
            f"  - lifeos\n"
            f"  - story\n"
            f"  - architecture\n"
            f"---\n\n"
        )
        final_markdown = frontmatter + body_content.strip()

        auth = Auth.Token(github_token)
        gh = Github(auth=auth)
        repo = gh.get_repo(github_repo)
        file_path = f"src/content/notes/LifeOS-Weekly-Dispatch--{today}.md"
        commit_message = f"content: weekly dispatch for {today}"

        # Idempotent: check if file exists → update, else create
        try:
            existing = repo.get_contents(file_path, ref="master")
            repo.update_file(
                path=file_path,
                message=commit_message,
                content=final_markdown,
                sha=existing.sha,
                branch="master",
            )
            print(f"✓ Updated {file_path} in {github_repo}")
        except Exception:
            repo.create_file(
                path=file_path,
                message=commit_message,
                content=final_markdown,
                branch="master",
            )
            print(f"✓ Created {file_path} in {github_repo}")
        return True
    except Exception as e:
        print(f"Failed to publish to GitHub: {e}")
        return False


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def _build_dispatch_prompt_from_digest(
    digest_content: str,
    url_refs: str,
    today: str,
) -> str:
    """Dispatch prompt using the pre-curated weekly digest as primary source."""
    return f"""You are Hermes, the LifeOS Intelligence Agent and private CTO.
Write a Weekly Dispatch blog post for the week of {today}.

Below is this week's curated TLDR digest — use it as your primary source.
Do NOT re-summarise or re-curate from scratch; the digest IS the curated content.

CRITICAL INSTRUCTIONS:
1. Top Stories: Pull the 5-7 most important stories from the digest. Cover at
   least 4 different topic areas. Do not let AI and Tech dominate.
2. Simplicity: Write Architecture Case Studies as if teaching a junior developer.
   Make the theory universal; use LifeOS as the practical implementation example.
3. LifeOS Context: Do not hallucinate fake agents. LifeOS currently only has
   "Hermes" (analyst) and "Prototyper" (coder).
4. DO NOT include meta-commentary about the generation process (no "Sample
   dispatch", no "generated for format review", no self-referential text).

{url_refs}

Weekly Digest:
{digest_content}

Structure your output EXACTLY matching this Markdown template:

# LifeOS Weekly Dispatch — {today}

---

## 🔥 Top Stories This Week
*Curated from the excellent daily [TLDR Newsletters](https://tldr.tech/).*

- **[[Article Title]](Original Article URL)**
  [Your original 2-3 sentence summary. Why it matters.]

[Repeat for each article]

---

## 🏗️ Architecture Case Studies

[For exactly 2 actionable insights this week, write a technical case study.]

### [Concept/Pattern Name]
*Inspired by: [[Article Name]](Original Article URL)*

#### The Core Concept
[2-3 paragraphs of accessible, easy-to-understand technical prose explaining the
mechanism thoroughly. Make the theory universal so any developer can learn from it.]

#### Architecture Diagram
```mermaid
[Mermaid block diagram. IMPORTANT: Do not use parentheses () or special characters
inside node labels unless you wrap the label in double quotes (e.g., A["Node (extra)"]).]
```

#### LifeOS Application
[1-2 paragraphs of clear prose explaining how this applies to LifeOS. This is a
design exploration — a blueprint for implementing the pattern in a real-world system.]

#### Trade-offs
[Brief paragraph discussing pros and cons]

[Repeat for exactly 2 case studies]

---

## 💡 Takeaway of the Week
[One opinionated paragraph synthesizing the biggest theme across all the week's
news. Written in first person, conversational tone.]

---"""


def _build_dispatch_prompt_fallback(
    articles_block: str,
    today: str,
    article_count: int,
) -> str:
    """Dispatch prompt from raw article full text (fallback path)."""
    return f"""You are Hermes, the LifeOS Intelligence Agent and private CTO.
Write a Weekly Dispatch blog post for the week of {today}.

You have the full text of {article_count} carefully selected articles below.
For each article, write your OWN original 2-3 sentence summary based on the full
content (NOT the TLDR blurb).

CRITICAL INSTRUCTIONS:
1. Top Stories: Curate the 5-7 most important stories from at least 4 different
   topics (e.g., AI, Web Dev, InfoSec, Founders, Design). Do not let AI and Tech
   dominate.
2. Simplicity: Write Architecture Case Studies as if teaching a junior developer.
3. LifeOS Context: Do not hallucinate fake agents. LifeOS currently only has
   "Hermes" (analyst) and "Prototyper" (coder).
4. DO NOT include meta-commentary about the generation process (no "Sample
   dispatch", no "generated for format review", no self-referential text).

Structure your output EXACTLY matching this Markdown template:

# LifeOS Weekly Dispatch — {today}

---

## 🔥 Top Stories This Week
*Curated from the excellent daily [TLDR Newsletters](https://tldr.tech/).*

- **[[Article Title]](Original Article URL)**
  [Your original 2-3 sentence summary. Why it matters.]

[Repeat for each article]

---

## 🏗️ Architecture Case Studies

[For exactly 2 actionable insights this week, write a technical case study.]

### [Concept/Pattern Name]
*Inspired by: [[Article Name]](Original Article URL)*

#### The Core Concept
[2-3 paragraphs of accessible, easy-to-understand technical prose explaining the
mechanism thoroughly. Make the theory universal so any developer can learn from it.]

#### Architecture Diagram
```mermaid
[Mermaid block diagram. IMPORTANT: Do not use parentheses () inside node labels
unless wrapped in double quotes (e.g., A["Node (extra)"]).]
```

#### LifeOS Application
[1-2 paragraphs of clear prose explaining how this applies to LifeOS. This is a
design exploration — a blueprint for implementing the pattern in a real-world system.]

#### Trade-offs
[Brief paragraph discussing pros and cons]

[Repeat for exactly 2 case studies]

---

## 💡 Takeaway of the Week
[One opinionated paragraph synthesizing the biggest theme across all the week's
news. Written in first person, conversational tone.]

---

*Generated by Hermes — LifeOS Weekly Intelligence Agent*
*Review, edit, and publish at your discretion. Nothing here goes public automatically.*

Here are the articles:
{articles_block}"""


def _build_proposal_prompt(articles_block: str, article_count: int) -> str:
    """Architecture proposal prompt (only used when ``INCLUDE_PROPOSALS=true``)."""
    return f"""You are Hermes, the LifeOS Intelligence Agent and private CTO.
Review the following {article_count} articles.
Write up to 3 short Architecture Proposals for LifeOS improvements based on
insights from these articles.

You MUST respond with a valid JSON array of objects. Do NOT wrap the JSON in
markdown code blocks, just raw JSON.
If no articles provide actionable architecture insights, return an empty array: []

Each object in the array must have two keys:
1. "filename": A short, snake_case filename (e.g., "proposal_agent_judge.md").
2. "content": The full Markdown content of the proposal.

The Markdown content MUST strictly follow this exact template:

# [Proposal Title]

## Problem
[Description of the problem based on the article]

## Proposed Solution
[How LifeOS can implement this]

## Source
[URL from the article]

## Status
Proposed

## Effort
[Small/Medium/Large]

Articles:
{articles_block}"""


# ---------------------------------------------------------------------------
# Fallback pipeline (raw articles → select → fetch → dispatch)
# ---------------------------------------------------------------------------

def _run_fallback_pipeline(today: str) -> tuple[str, list[dict]]:
    """Original two-phase pipeline from raw TLDR articles.

    Used only when no weekly digest is available.
    Returns ``(dispatch_markdown, proposals_list)``.
    """
    from src.core.llm_client import parse_json_safely  # noqa: E402

    # Collect articles
    print("Collecting articles from last 7 days...")
    articles = collect_articles_from_notes(days=7)
    print(f"Found {len(articles)} unique article candidates.")

    if not articles:
        print("No articles found. Exiting.")
        return "", []

    # Phase 1: LLM selects top 5-7 stories from metadata
    candidates_text = build_candidates_prompt(articles)
    if len(candidates_text) > 60000:
        candidates_text = candidates_text[:60000] + "\n\n[... truncated ...]"

    selection_prompt = (
        "You are Hermes, a senior tech intelligence analyst.\n\n"
        f"Below is a list of {len(articles)} articles from this week's tech newsletters.\n\n"
        "Pick the 5-7 most important, high-signal stories that a senior software "
        "engineer and CTO would care about.\n\n"
        "CRITICAL DIVERSITY RULE: You MUST select stories from at least 4 different "
        "newsletter sources/topics (look at the Source URL). Do not let AI and Tech "
        "dominate the entire list. Pick from InfoSec, Web Dev, Founders, Design, Data, etc.\n\n"
        "Prioritize:\n"
        "- Breakthrough research or paradigm shifts\n"
        "- Security advisories or CVEs\n"
        "- Major product launches or API changes\n"
        "- Architectural patterns or best practices\n\n"
        "Respond with ONLY a JSON array of the selected article numbers (1-indexed). "
        "Example: [3, 7, 12, 15, 22]\n\n"
        f"Articles:\n{candidates_text}"
    )

    print("Phase 1: Asking LLM to select top stories...")
    selection_response = call_llm(
        prompt=selection_prompt,
        system_prompt="You are a tech analyst. Respond with only a JSON array of numbers.",
        max_tokens=200,
        temperature=0.2,
    )

    if not selection_response:
        print("LLM selection failed. Falling back to 5 random articles.")
        selected_articles = random.sample(articles, min(5, len(articles)))
    else:
        print(f"LLM response: {selection_response}")  # codeql[py/clear-text-logging-sensitive-data]
        try:
            nums_match = re.search(r"\[[\d,\s]+\]", selection_response)
            if nums_match:
                indices = [int(x) for x in re.findall(r"\d+", nums_match.group())]
                selected_articles = [
                    articles[i - 1] for i in indices if 0 < i <= len(articles)
                ]
            else:
                selected_articles = random.sample(articles, min(5, len(articles)))
        except Exception:
            selected_articles = random.sample(articles, min(5, len(articles)))

    print(f"Selected {len(selected_articles)} articles for deep fetch.")

    # Phase 2: Fetch full text of selected articles
    enriched: list[dict] = []
    for art in selected_articles:
        print(f"  Fetching: {art['title'][:60]}...")
        try:
            _title, full_text = fetch_webpage_content(art["url"])
            if full_text and len(full_text) > FETCH_CAP_CHARS:
                full_text = full_text[:FETCH_CAP_CHARS] + "\n\n[... truncated ...]"
            art["full_text"] = full_text or art.get("summary", "")
            enriched.append(art)
        except Exception as exc:
            print(f"    Failed: {exc}")
            art["full_text"] = art.get("summary", "No content available.")
            enriched.append(art)

    # Build articles block for prompts
    articles_block = ""
    for i, art in enumerate(enriched, 1):
        articles_block += f"\n--- Article {i} ---\n"
        articles_block += f"Title: {art['title']}\n"
        articles_block += f"Source: {art['source']}\n"
        articles_block += f"URL: {art['url']}\n"
        articles_block += f"Full Text:\n{art['full_text']}\n"

    # Phase 2a: Proposals (only when explicitly enabled)
    proposals_list: list[dict] = []
    if os.environ.get("INCLUDE_PROPOSALS", "").lower() == "true":
        print("Phase 2a: Generating architecture proposals (INCLUDE_PROPOSALS=true)...")
        proposals_raw = call_llm(
            prompt=_build_proposal_prompt(articles_block, len(enriched)),
            system_prompt="You are Hermes, a brilliant CTO. Respond ONLY with valid JSON.",
            max_tokens=3000,
            temperature=0.2,
        )
        if proposals_raw:
            proposals_list = parse_json_safely(proposals_raw)
            if not isinstance(proposals_list, list):
                proposals_list = []
        if not proposals_list:
            print(
                "WARNING: LLM failed to generate proposals (or returned empty list). "
                "Skipping proposals.",
            )
    else:
        print("Proposals disabled (set INCLUDE_PROPOSALS=true to enable).")

    # Phase 2b: Dispatch generation
    print("Phase 2b: Generating dispatch...")
    dispatch = call_llm(
        prompt=_build_dispatch_prompt_fallback(articles_block, today, len(enriched)),
        system_prompt=(
            "You are Hermes, a brilliant CTO writing a weekly newsletter. "
            "Do not include literal instructions in your output."
        ),
        max_tokens=DISPATCH_MAX_TOKENS,
        temperature=DISPATCH_TEMPERATURE,
    )

    return dispatch or "", proposals_list


# ---------------------------------------------------------------------------
# Main Pipeline
# ---------------------------------------------------------------------------

@execute_with_repair(mode="background")
def run_weekly_pipeline() -> None:
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    print("--- Starting Weekly Hermes Pipeline ---")

    # 1. Run outbox triage
    print("Running outbox triage...")
    triage_notes()

    # 2. Try digest-first approach; fall back to raw articles if no digest
    digest_path = find_latest_digest()
    proposals_list: list[dict] = []

    if digest_path:
        try:
            digest_display = digest_path.relative_to(BASE_DIR)
        except ValueError:
            digest_display = digest_path
        print(f"Found weekly digest: {digest_display}")
        digest_content = digest_path.read_text(encoding="utf-8")

        # Collect article URLs for cross-referencing in the dispatch
        articles = collect_articles_from_notes(days=7)
        print(f"Collected {len(articles)} articles for URL metadata.")
        url_refs = build_url_reference(articles)

        # Generate dispatch from digest (single LLM call)
        print("Generating dispatch from weekly digest...")
        dispatch = call_llm(
            prompt=_build_dispatch_prompt_from_digest(digest_content, url_refs, today),
            system_prompt=(
                "You are Hermes, a brilliant CTO writing a weekly newsletter. "
                "Do not include literal instructions in your output."
            ),
            max_tokens=DISPATCH_MAX_TOKENS,
            temperature=DISPATCH_TEMPERATURE,
        )

        # Proposals (only when explicitly enabled — default: off)
        if os.environ.get("INCLUDE_PROPOSALS", "").lower() == "true":
            from src.core.llm_client import parse_json_safely  # noqa: E402

            print("Generating architecture proposals (INCLUDE_PROPOSALS=true)...")
            proposals_raw = call_llm(
                prompt=_build_proposal_prompt(
                    f"Digest content:\n{digest_content[:6000]}\n\n{url_refs}",
                    len(articles),
                ),
                system_prompt=(
                    "You are Hermes, a brilliant CTO. Respond ONLY with valid JSON."
                ),
                max_tokens=3000,
                temperature=0.2,
            )
            if proposals_raw:
                proposals_list = parse_json_safely(proposals_raw)
                if not isinstance(proposals_list, list):
                    proposals_list = []
    else:
        # Fallback: raw article pipeline
        print("No digest found. Falling back to raw article pipeline...")
        dispatch, proposals_list = _run_fallback_pipeline(today)

    # 3. Sanitise output
    dispatch = strip_artifacts(dispatch or "")

    if not dispatch:
        print(
            "WARNING: LLM failed to generate dispatch (possible content filter). "
            "Using placeholder.",
        )
        dispatch = (
            "_No dispatch generated this week due to content filters or API errors._"
        )

    # 4. Save dispatch locally
    out_dir = BASE_DIR / "data" / "inbox" / "content_drafts"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"weekly_dispatch_{today}.md"
    out_file.write_text(dispatch, encoding="utf-8")  # codeql[py/clear-text-storage-sensitive-data]
    print(f"✓ Weekly dispatch saved: {out_file.relative_to(BASE_DIR)}")

    # 5. Save proposals (if any were generated)
    if proposals_list:
        prop_dir = BASE_DIR / "data" / "inbox" / "proposals"
        prop_dir.mkdir(parents=True, exist_ok=True)
        for prop in proposals_list:
            filename = prop.get("filename", f"proposal_{today}.md")
            if not filename.endswith(".md"):
                filename += ".md"
            prop_file = prop_dir / filename
            prop_file.write_text(
                prop.get("content", ""), encoding="utf-8",
            )  # codeql[py/clear-text-storage-sensitive-data]
            print(f"✓ Proposal saved: {prop_file.relative_to(BASE_DIR)}")  # codeql[py/clear-text-logging-sensitive-data]

    # 6. Update outbox DB
    if DB_PATH.exists():
        conn = get_db_connection(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            SELECT id FROM automation_outbox
            WHERE is_actionable = 1
              AND processed_at IS NOT NULL
              AND hermes_run_at IS NULL
        """)
        row_ids = [r[0] for r in cursor.fetchall()]
        if row_ids:
            now_str = (
                datetime.datetime.now(datetime.timezone.utc)
                .astimezone()
                .isoformat()
            )
            placeholders = ",".join("?" for _ in row_ids)
            cursor.execute(
                f"UPDATE automation_outbox SET hermes_run_at = ? WHERE id IN ({placeholders})",
                [now_str] + row_ids,
            )
            conn.commit()
            print(f"✓ Marked {len(row_ids)} outbox items as processed.")
        conn.close()

    # 7. Push to GitHub (idempotent — handles both create and update)
    push_to_github(dispatch, today)

    print("--- Pipeline Complete ---")


if __name__ == "__main__":
    run_weekly_pipeline()
